global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'needstation-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']
    scrape_timeout: 3s

  - job_name: 'needstation-health'
    metrics_path: '/actuator/health'
    scrape_interval: 30s
    static_configs:
      - targets: ['app:8080']
