package com.example.authbackend.model;

public enum WorkerType {
    NURSE,
    CAREGIVER,
    CARETAKER,
    ELDER_CARE,
    PHYSIOTHERAPIST,
    ATTENDANT,
    MEDICAL_ASSISTANT,
    HOME_NURSE,
    ICU_NURSE,
    PEDIATRIC_NURSE,
    GERIATRIC_NURSE,
    REHABILITATION_SPECIALIST,
    MEDICAL_TECHNICIAN,
    OTHER
}
