package com.example.authbackend.service;

import com.example.authbackend.dto.BookingResponseDTO;
import com.example.authbackend.dto.CreateBookingDTO;
import com.example.authbackend.model.*;
import com.example.authbackend.repository.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
public class BookingServiceNew {
    
    @Autowired
    private BookingNewRepository bookingRepository;
    
    @Autowired
    private BookingSubServiceRepository bookingSubServiceRepository;
    
    @Autowired
    private BookingFormalityDataRepository bookingFormalityDataRepository;
    
    @Autowired
    private ServiceFormalityRepository serviceFormalityRepository;
    
    @Autowired
    private ServiceService serviceService;
    
    @Autowired
    private UserRepository userRepository;
    
    private final ObjectMapper objectMapper = new ObjectMapper();
    
    /**
     * Create a new booking
     */
    @Transactional
    public BookingResponseDTO createBooking(CreateBookingDTO dto) {
        try {
            System.out.println("📝 Creating booking for userId: " + dto.getUserId() + ", serviceId: " + dto.getServiceId());
            
            // 1. Get service details
            com.example.authbackend.model.Service service = serviceService.getServiceById(dto.getServiceId());
            System.out.println("✅ Service found: " + service.getServiceName());
            
            // 2. Get user details
            User user = userRepository.findById(dto.getUserId())
                    .orElseThrow(() -> new RuntimeException("User not found with ID: " + dto.getUserId()));
            System.out.println("✅ User found: " + user.getUsername());
            
            // 3. Calculate total amount
            BigDecimal totalAmount = calculateTotalAmount(service, dto.getSelectedSubServices());
            System.out.println("✅ Total amount calculated: " + totalAmount);
        
        // 4. Create booking record
        BookingNew booking = new BookingNew();
        booking.setUserId(dto.getUserId());
        booking.setServiceId(dto.getServiceId());
        
        // Denormalized fields (will be auto-filled by trigger, but set manually for safety)
        booking.setServiceName(service.getServiceName());
        booking.setServiceCode(service.getServiceCode());
        
        // Handle user name - fallback to username if fullName is null
        String userName = user.getFullName();
        if (userName == null || userName.trim().isEmpty()) {
            userName = user.getUsername();
        }
        booking.setUserName(userName);
        booking.setUserEmail(user.getEmail());
        
        // Contact & Location
        CreateBookingDTO.ContactInfo contact = dto.getContactInfo();
        booking.setPhone(contact.getPhone());
        booking.setAlternatePhone(contact.getAlternatePhone());
        booking.setFullAddress(contact.getFullAddress());
        booking.setLandmark(contact.getLandmark());
        booking.setCity(contact.getCity());
        booking.setState(contact.getState());
        booking.setPincode(contact.getPincode());
        booking.setLocationLat(contact.getLocationLat());
        booking.setLocationLng(contact.getLocationLng());
        booking.setLocationAddress(contact.getLocationAddress());
        
        // Scheduling
        CreateBookingDTO.Scheduling scheduling = dto.getScheduling();
        booking.setPreferredDate(scheduling.getPreferredDate());
        booking.setPreferredTime(scheduling.getPreferredTime());
        booking.setPreferredTimeSlot(scheduling.getPreferredTimeSlot());
        booking.setUrgency(scheduling.getUrgency());
        
        // Pricing
        booking.setBaseAmount(service.getBasePrice());
        booking.setAdditionalCharges(totalAmount.subtract(service.getBasePrice()));
        booking.setTotalAmount(totalAmount);
        
        // Status
        booking.setStatus("PENDING");
        booking.setPaymentStatus("PENDING");
        
        // Special instructions
        booking.setSpecialInstructions(dto.getSpecialInstructions());
        
        // Audit
        booking.setCreatedBy(dto.getUserId());
        
        // Save booking (booking_number will be auto-generated by trigger)
        booking = bookingRepository.save(booking);
        
        // 5. Create booking subservices
        List<String> subServiceNames = new ArrayList<>();
        if (dto.getSelectedSubServices() != null && !dto.getSelectedSubServices().isEmpty()) {
            for (Long subServiceId : dto.getSelectedSubServices()) {
                SubService subService = serviceService.getSubServiceById(subServiceId);
                
                BookingSubService bss = new BookingSubService();
                bss.setBooking(booking);
                bss.setSubServiceId(subServiceId);
                bss.setSubServiceName(subService.getSubServiceName());
                bss.setQuantity(1);
                bss.setPrice(subService.getAdditionalPrice());
                
                bookingSubServiceRepository.save(bss);
                subServiceNames.add(subService.getSubServiceName());
            }
        }
        
        // 6. Create booking formality data
        Map<String, String> formalityDataMap = new HashMap<>();
        if (dto.getFormalityData() != null && !dto.getFormalityData().isEmpty()) {
            for (Map.Entry<String, String> entry : dto.getFormalityData().entrySet()) {
                String fieldName = entry.getKey();
                String fieldValue = entry.getValue();
                
                // Find formality by field name
                ServiceFormality formality = serviceFormalityRepository.findByServiceIdNotDeleted(dto.getServiceId())
                        .stream()
                        .filter(f -> f.getFieldName().equals(fieldName))
                        .findFirst()
                        .orElse(null);
                
                if (formality != null) {
                    BookingFormalityData bfd = new BookingFormalityData();
                    bfd.setBooking(booking);
                    bfd.setFormalityId(formality.getId());
                    bfd.setFieldName(formality.getFieldName());
                    bfd.setFieldLabel(formality.getFieldLabel());
                    bfd.setFieldValue(fieldValue);
                    
                    bookingFormalityDataRepository.save(bfd);
                    formalityDataMap.put(fieldName, fieldValue);
                }
            }
        }
        
        // 7. Build response DTO
        BookingResponseDTO response = new BookingResponseDTO();
        response.setId(booking.getId());
        response.setBookingNumber(booking.getBookingNumber());
        response.setStatus(booking.getStatus());
        response.setPaymentStatus(booking.getPaymentStatus());
        response.setTotalAmount(booking.getTotalAmount());
        response.setPreferredDate(booking.getPreferredDate());
        response.setPreferredTime(booking.getPreferredTime());
        response.setPreferredTimeSlot(booking.getPreferredTimeSlot());
        response.setUrgency(booking.getUrgency());
        response.setCreatedAt(booking.getCreatedAt());
        response.setServiceName(booking.getServiceName());
        response.setServiceCode(booking.getServiceCode());
        response.setUserName(booking.getUserName());
        response.setPhone(booking.getPhone());
        response.setSubServices(subServiceNames);
        response.setSubservicesCount(subServiceNames.size());
        response.setFormalityData(formalityDataMap);
        response.setFullAddress(booking.getFullAddress());
        response.setCity(booking.getCity());
        
        System.out.println("✅ Booking created successfully: " + response.getBookingNumber());
        return response;
        
        } catch (Exception e) {
            System.err.println("❌ Error creating booking: " + e.getMessage());
            e.printStackTrace();
            throw new RuntimeException("Failed to create booking: " + e.getMessage(), e);
        }
    }
    
    /**
     * Get user's bookings
     */
    public List<BookingResponseDTO> getUserBookings(Long userId) {
        List<BookingNew> bookings = bookingRepository.findByUserIdNotDeleted(userId);
        
        return bookings.stream()
                .map(this::convertToResponseDTO)
                .collect(Collectors.toList());
    }
    
    /**
     * Get booking by ID
     */
    public BookingResponseDTO getBookingById(Long bookingId) {
        BookingNew booking = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new RuntimeException("Booking not found"));
        
        return convertToDetailedResponseDTO(booking);
    }
    
    /**
     * Get booking by booking number
     */
    public BookingResponseDTO getBookingByNumber(String bookingNumber) {
        BookingNew booking = bookingRepository.findByBookingNumber(bookingNumber)
                .orElseThrow(() -> new RuntimeException("Booking not found"));
        
        return convertToDetailedResponseDTO(booking);
    }
    
    /**
     * Update booking status
     */
    @Transactional
    public BookingResponseDTO updateBookingStatus(Long bookingId, String status, Long updatedBy) {
        BookingNew booking = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new RuntimeException("Booking not found"));
        
        booking.setStatus(status);
        booking.setUpdatedBy(updatedBy);
        
        if ("COMPLETED".equals(status)) {
            booking.setCompletedAt(LocalDateTime.now());
        } else if ("CANCELLED".equals(status)) {
            booking.setCancelledAt(LocalDateTime.now());
            booking.setCancelledBy(updatedBy);
        } else if ("IN_PROGRESS".equals(status)) {
            booking.setStartedAt(LocalDateTime.now());
        }
        
        booking = bookingRepository.save(booking);
        
        return convertToResponseDTO(booking);
    }
    
    /**
     * Assign worker to booking
     */
    @Transactional
    public BookingResponseDTO assignWorker(Long bookingId, Long workerId, Long updatedBy) {
        BookingNew booking = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new RuntimeException("Booking not found"));
        
        booking.setAssignedWorkerId(workerId);
        booking.setStatus("ASSIGNED");
        booking.setUpdatedBy(updatedBy);
        
        booking = bookingRepository.save(booking);
        
        return convertToResponseDTO(booking);
    }
    
    /**
     * Rate booking
     */
    @Transactional
    public BookingResponseDTO rateBooking(Long bookingId, Integer rating, String feedback) {
        BookingNew booking = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new RuntimeException("Booking not found"));
        
        if (!"COMPLETED".equals(booking.getStatus())) {
            throw new RuntimeException("Can only rate completed bookings");
        }
        
        booking.setCustomerRating(rating);
        booking.setCustomerFeedback(feedback);
        
        booking = bookingRepository.save(booking);
        
        return convertToResponseDTO(booking);
    }
    
    /**
     * Calculate total amount
     */
    private BigDecimal calculateTotalAmount(com.example.authbackend.model.Service service, List<Long> subServiceIds) {
        BigDecimal total = service.getBasePrice();
        
        if (subServiceIds != null && !subServiceIds.isEmpty()) {
            for (Long subServiceId : subServiceIds) {
                SubService subService = serviceService.getSubServiceById(subServiceId);
                total = total.add(subService.getAdditionalPrice());
            }
        }
        
        return total;
    }
    
    /**
     * Convert booking to response DTO (simple)
     */
    private BookingResponseDTO convertToResponseDTO(BookingNew booking) {
        BookingResponseDTO dto = new BookingResponseDTO();
        dto.setId(booking.getId());
        dto.setBookingNumber(booking.getBookingNumber());
        dto.setStatus(booking.getStatus());
        dto.setPaymentStatus(booking.getPaymentStatus());
        dto.setTotalAmount(booking.getTotalAmount());
        dto.setPreferredDate(booking.getPreferredDate());
        dto.setPreferredTime(booking.getPreferredTime());
        dto.setPreferredTimeSlot(booking.getPreferredTimeSlot());
        dto.setUrgency(booking.getUrgency());
        dto.setCreatedAt(booking.getCreatedAt());
        dto.setServiceName(booking.getServiceName());
        dto.setServiceCode(booking.getServiceCode());
        dto.setUserName(booking.getUserName());
        dto.setPhone(booking.getPhone());
        dto.setAssignedWorkerName(booking.getAssignedWorkerName());
        dto.setSubservicesCount(booking.getSubservicesCount());
        dto.setFullAddress(booking.getFullAddress());
        dto.setCity(booking.getCity());
        dto.setCustomerRating(booking.getCustomerRating());
        dto.setCustomerFeedback(booking.getCustomerFeedback());
        
        // Parse subservices summary
        if (booking.getSubservicesSummary() != null) {
            try {
                List<String> subServices = objectMapper.readValue(
                        booking.getSubservicesSummary(),
                        objectMapper.getTypeFactory().constructCollectionType(List.class, String.class)
                );
                dto.setSubServices(subServices);
            } catch (JsonProcessingException e) {
                dto.setSubServices(new ArrayList<>());
            }
        }
        
        return dto;
    }
    
    /**
     * Convert booking to detailed response DTO (with formality data)
     */
    private BookingResponseDTO convertToDetailedResponseDTO(BookingNew booking) {
        BookingResponseDTO dto = convertToResponseDTO(booking);
        
        // Get formality data
        List<BookingFormalityData> formalityDataList = bookingFormalityDataRepository.findByBookingId(booking.getId());
        Map<String, String> formalityMap = formalityDataList.stream()
                .collect(Collectors.toMap(
                        BookingFormalityData::getFieldName,
                        BookingFormalityData::getFieldValue
                ));
        dto.setFormalityData(formalityMap);
        
        // Get subservices
        List<BookingSubService> subServices = bookingSubServiceRepository.findByBookingId(booking.getId());
        List<String> subServiceNames = subServices.stream()
                .map(BookingSubService::getSubServiceName)
                .collect(Collectors.toList());
        dto.setSubServices(subServiceNames);
        
        return dto;
    }
}
